version: "3.9"

networks:
  default:
    name: pingnw
    driver: bridge

services:
  pingack:
    depends_on:
      - jaeger
    build:
      context: ./ping-ack-api/
    pid: "host"
    ports:
      - "7997:7997"
    volumes:
      - /proc:/host/proc

  # auto instrument golang app
  go-auto:
    depends_on:
      - pingack
    image: otel/autoinstrumentation-go
    privileged: true
    pid: "host"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318
      - OTEL_GO_AUTO_TARGET_EXE=/app/main
      - OTEL_SERVICE_NAME=pingack
      - OTEL_PROPAGATORS=tracecontext,baggage
    volumes:
      - /proc:/host/proc

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268:14268"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=debug
    deploy:
      resources:
        limits:
          memory: 300M
    restart: unless-stopped

